import { z } from 'zod';
import { ItemType, ItemStatus, EventCategory, RepeatType, StageEnum, ActivitiesEnum } from '@prisma/client';

const createSchema = z.object({
  childIds: z.array(z.string({ error: 'childIds is required' })),
  providerId: z.string({ error: 'providerId is required' }).optional(),
  itemType: z.enum(ItemType, { error: 'itemType is required' }),
  title: z.string({ error: 'title is required' }),
  description: z.string({ error: 'description is required' }).optional(),
  link: z.string({ error: 'link is required' }).optional(),
  fileUrl: z.string({ error: 'fileUrl is required' }).optional(),
  notes: z.string({ error: 'notes is required' }).optional(),
  startDate: z.coerce.date({ error: 'startDate is required' }).optional(),
  endDate: z.coerce.date({ error: 'endDate is required' }).optional(),
  startTime: z.string({ error: 'startTime is required' }).optional(),
  endTime: z.string({ error: 'endTime is required' }).optional(),
  duration: z.number({ error: 'duration is required' }).int().optional(),
  daysPWeek: z.number({ error: 'daysPWeek is required' }).int().optional(),
  days: z.array(z.string({ error: 'days is required' })),
  isAddedCalender: z.boolean({ error: 'isAddedCalender is required' }).optional(),
  isForAllChild: z.boolean({ error: 'isForAllChild is required' }).optional(),
  eventCategory: z.enum(EventCategory, { error: 'eventCategory is required' }).optional(),
  location: z.string({ error: 'location is required' }).optional(),
  weeks: z.number({ error: 'weeks is required' }).int().optional(),
  reminderTime: z.number({ error: 'reminderTime is required' }).int().optional(),
  repeatType: z.enum(RepeatType, { error: 'repeatType is required' }).optional(),
  repeatEndDate: z.coerce.date({ error: 'repeatEndDate is required' }).optional(),
  stage: z.enum(StageEnum, { error: 'stage is required' }).optional(),
  activityType: z.enum(ActivitiesEnum, { error: 'activityType is required' }).optional(),
  skill: z.array(z.string({ error: 'skill is required' })),
  materials: z.string({ error: 'materials is required' }).optional(),
  howToDoIt: z.string({ error: 'howToDoIt is required' }).optional(),
  whatItHelpsWith: z.string({ error: 'whatItHelpsWith is required' }).optional(),
});

const updateSchema = z.object({
  childIds: z.array(z.string({ error: 'childIds is required' })).optional(),
  providerId: z.string({ error: 'providerId is required' }).optional(),
  itemType: z.enum(ItemType, { error: 'itemType is required' }).optional(),
  title: z.string({ error: 'title is required' }).optional(),
  description: z.string({ error: 'description is required' }).optional(),
  link: z.string({ error: 'link is required' }).optional(),
  fileUrl: z.string({ error: 'fileUrl is required' }).optional(),
  notes: z.string({ error: 'notes is required' }).optional(),
  startDate: z.coerce.date({ error: 'startDate is required' }).optional(),
  endDate: z.coerce.date({ error: 'endDate is required' }).optional(),
  startTime: z.string({ error: 'startTime is required' }).optional(),
  endTime: z.string({ error: 'endTime is required' }).optional(),
  duration: z.number({ error: 'duration is required' }).int().optional(),
  daysPWeek: z.number({ error: 'daysPWeek is required' }).int().optional(),
  days: z.array(z.string({ error: 'days is required' })).optional(),
  isAddedCalender: z.boolean({ error: 'isAddedCalender is required' }).optional(),
  isForAllChild: z.boolean({ error: 'isForAllChild is required' }).optional(),
  eventCategory: z.enum(EventCategory, { error: 'eventCategory is required' }).optional(),
  location: z.string({ error: 'location is required' }).optional(),
  weeks: z.number({ error: 'weeks is required' }).int().optional(),
  reminderTime: z.number({ error: 'reminderTime is required' }).int().optional(),
  repeatType: z.enum(RepeatType, { error: 'repeatType is required' }).optional(),
  repeatEndDate: z.coerce.date({ error: 'repeatEndDate is required' }).optional(),
  stage: z.enum(StageEnum, { error: 'stage is required' }).optional(),
  activityType: z.enum(ActivitiesEnum, { error: 'activityType is required' }).optional(),
  skill: z.array(z.string({ error: 'skill is required' })).optional(),
  materials: z.string({ error: 'materials is required' }).optional(),
  howToDoIt: z.string({ error: 'howToDoIt is required' }).optional(),
  whatItHelpsWith: z.string({ error: 'whatItHelpsWith is required' }).optional(),
});

export const scheduleItemValidation = {
  createSchema,
  updateSchema,
};